target("test_mlp")
    add_files("test_mlp.cpp")
    add_deps("global", "layers", "loss", "gpu_rands")
    add_deps("lc-runtime", "lc-core")
    add_deps("stb-image")
    add_deps("lc-gui")
    set_rundir("$(projectdir)")
target_end()

target("test_mlp_clear")
    add_files("test_mlp_clear.cpp")
    add_deps("global", "layers", "loss", "gpu_rands")
    add_deps("lc-runtime", "lc-core")
    add_deps("stb-image")
    add_deps("lc-gui")
    set_rundir("$(projectdir)")
target_end()