includes("global")
includes("networks")
includes("util")
includes("programs")

target("test8")
    set_kind("binary")
    add_files("main.cpp")
    add_deps("global", "matmuls", "gpu_rands")
    add_deps("lc-runtime", "lc-core")